# Rare-word sparse retrieval — diagnostics

| Section | What runs | Gate |
|---|---|---|
| Step 1 | `rarity` — the frozen 500-word list | the head of the list is vocabulary, not tokenizer debris |
| Step 2 | `leakage` — near-duplicate audit, quarantine | few enough flags that quarantining leaves the pool intact |
| Step 3 | `sparse_select` — selection dry run | full dose ≥ 30% of val queries, else report and stop |

In [18]:
# e5-large in fp32 over a 10.8k-row pool; any Colab GPU is enough.
!nvidia-smi --query-gpu=name,memory.total --format=csv

name, memory.total [MiB]
NVIDIA GeForce RTX 4060 Laptop GPU, 8188 MiB

In [19]:
%cd /home/prnamhr/projects/Style-Aware-MT
!pip install -r requirements.txt

# Text-only pipeline; these two carry an ABI mismatch against the pinned torch.
!pip uninstall -y torchvision torchaudio

/home/prnamhr/projects/Style-Aware-MT
Requirement already satisfied: sentence-transformers==5.5.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (5.5.1)
Requirement already satisfied: torch==2.12.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (2.12.0)
Requirement already satisfied: transformers==5.12.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (5.12.1)
Requirement already satisfied: accelerate==1.14.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: bitsandbytes==0.49.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (0.49.2)
Requirement already satisfied: peft==0.18.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.18.0)
Requirement already satisfied: trl==1.9.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (1.9.2)
Requirement already satisfied: openai==2.41.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (2.41.1)
Requirement already satisfied: anthropic==0.109.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (0.109.1)
Requirement already satisfied: google-genai==2.12.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (2.12.1)
Requirement already satisfied: sacrebleu==2.6.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (2.6.0)
Requirement already satisfied: matplotlib==3.11.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (3.11.1)
Requirement already satisfied: PyYAML==6.0.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 13)) (6.0.3)
Requirement already satisfied: python-dotenv==1.2.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 14)) (1.2.2)
Requirement already satisfied: asttokens==3.0.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (3.0.1)
Requirement already satisfied: comm==0.2.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 16)) (0.2.3)
Requirement already satisfied: debugpy==1.8.19 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 17)) (1.8.19)
Requirement already satisfied: decorator==5.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 18)) (5.2.1)
Requirement already satisfied: executing==2.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 19)) (2.2.1)
Requirement already satisfied: ipykernel==7.1.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 20)) (7.1.0)
Requirement already satisfied: ipython==9.9.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 21)) (9.9.0)
Requirement already satisfied: ipython_pygments_lexers==1.1.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 22)) (1.1.1)
Requirement already satisfied: jedi==0.19.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 23)) (0.19.2)
Requirement already satisfied: joblib==1.5.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 24)) (1.5.3)
Requirement already satisfied: jupyter_client==8.8.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 25)) (8.8.0)
Requirement already satisfied: jupyter_core==5.9.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 26)) (5.9.1)
Requirement already satisfied: lxml==6.0.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 27)) (6.0.2)
Requirement already satisfied: matplotlib-inline==0.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 28)) (0.2.1)
Requirement already satisfied: nest-asyncio==1.6.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 29)) (1.6.0)
Requirement already satisfied: numpy==2.4.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 30)) (2.4.1)
Requirement already satisfied: packaging==25.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 31)) (25.0)
Requirement already satisfied: pandas==2.3.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 32)) (2.3.3)
Requirement already satisfied: parso==0.8.5 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 33)) (0.8.5)
Requirement already satisfied: pexpect==4.9.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 34)) (4.9.0)
Requirement already satisfied: platformdirs==4.5.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 35)) (4.5.1)
Requirement already satisfied: prompt_toolkit==3.0.52 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 36)) (3.0.52)
Requirement already satisfied: psutil==7.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 37)) (7.2.1)
Requirement already satisfied: ptyprocess==0.7.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 38)) (0.7.0)
Requirement already satisfied: pure_eval==0.2.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 39)) (0.2.3)
Requirement already satisfied: Pygments==2.19.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 40)) (2.19.2)
Requirement already satisfied: python-dateutil==2.9.0.post0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 41)) (2.9.0.post0)
Requirement already satisfied: python-docx==1.2.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 42)) (1.2.0)
Requirement already satisfied: pytz==2025.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 43)) (2025.2)
Requirement already satisfied: pyzmq==27.1.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 44)) (27.1.0)
Requirement already satisfied: scikit-learn==1.8.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 45)) (1.8.0)
Requirement already satisfied: scipy==1.17.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 46)) (1.17.0)
Requirement already satisfied: six==1.17.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 47)) (1.17.0)
Requirement already satisfied: stack-data==0.6.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 48)) (0.6.3)
Requirement already satisfied: threadpoolctl==3.6.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 49)) (3.6.0)
Requirement already satisfied: tornado==6.5.4 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 50)) (6.5.4)
Requirement already satisfied: traitlets==5.14.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 51)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 52)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 53)) (2025.3)
Requirement already satisfied: wcwidth==0.2.14 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 54)) (0.2.14)
Requirement already satisfied: huggingface-hub>=0.23.0 in ./.venv/lib/python3.11/site-packages (from sentence-transformers==5.5.1->-r requirements.txt (line 1)) (1.28.0)
Requirement already satisfied: tqdm>=4.0.0 in ./.venv/lib/python3.11/site-packages (from sentence-transformers==5.5.1->-r requirements.txt (line 1)) (4.68.3)
Requirement already satisfied: regex>=2025.10.22 in ./.venv/lib/python3.11/site-packages (from transformers==5.12.1->-r requirements.txt (line 3)) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.11/site-packages (from transformers==5.12.1->-r requirements.txt (line 3)) (0.22.2)
Requirement already satisfied: typer in ./.venv/lib/python3.11/site-packages (from transformers==5.12.1->-r requirements.txt (line 3)) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.11/site-packages (from transformers==5.12.1->-r requirements.txt (line 3)) (0.8.0)
Requirement already satisfied: filelock in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.29.5)
Requirement already satisfied: setuptools<82 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (79.0.1)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.6.1)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (2026.6.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.2)
Requirement already satisfied: nvidia-cublas<=13.1.1.3,>=13.1.0.3 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (13.1.1.3)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.4.5)
Requirement already satisfied: triton==3.7.0 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.7.0)
Requirement already satisfied: datasets>=4.7.0 in ./.venv/lib/python3.11/site-packages (from trl==1.9.2->-r requirements.txt (line 7)) (5.0.1)
Requirement already satisfied: anyio<5,>=3.5.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (4.14.1)
Requirement already satisfied: distro<2,>=1.7.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (0.16.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (2.13.4)
Requirement already satisfied: sniffio in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (1.3.1)
Requirement already satisfied: docstring-parser<1,>=0.15 in ./.venv/lib/python3.11/site-packages (from anthropic==0.109.1->-r requirements.txt (line 9)) (0.18.0)
Requirement already satisfied: google-auth<2.56.0,>=2.48.1 in ./.venv/lib/python3.11/site-packages (from google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (2.55.2)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in ./.venv/lib/python3.11/site-packages (from google-genai==2.12.1->-r requirements.txt (line 10)) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in ./.venv/lib/python3.11/site-packages (from google-genai==2.12.1->-r requirements.txt (line 10)) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in ./.venv/lib/python3.11/site-packages (from google-genai==2.12.1->-r requirements.txt (line 10)) (16.1.1)
Requirement already satisfied: portalocker in ./.venv/lib/python3.11/site-packages (from sacrebleu==2.6.0->-r requirements.txt (line 11)) (3.2.0)
Requirement already satisfied: tabulate>=0.8.9 in ./.venv/lib/python3.11/site-packages (from sacrebleu==2.6.0->-r requirements.txt (line 11)) (0.10.0)
Requirement already satisfied: colorama in ./.venv/lib/python3.11/site-packages (from sacrebleu==2.6.0->-r requirements.txt (line 11)) (0.4.6)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (1.5.0)
Requirement already satisfied: pillow>=9 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (12.3.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (3.3.2)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.85)
Requirement already satisfied: idna>=2.8 in ./.venv/lib/python3.11/site-packages (from anyio<5,>=3.5.0->openai==2.41.1->-r requirements.txt (line 8)) (3.18)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in ./.venv/lib/python3.11/site-packages (from cuda-bindings<14,>=13.0.3->torch==2.12.0->-r requirements.txt (line 2)) (1.5.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.venv/lib/python3.11/site-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in ./.venv/lib/python3.11/site-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (49.0.0)
Requirement already satisfied: certifi in ./.venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai==2.41.1->-r requirements.txt (line 8)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai==2.41.1->-r requirements.txt (line 8)) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai==2.41.1->-r requirements.txt (line 8)) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in ./.venv/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers==5.5.1->-r requirements.txt (line 1)) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in ./.venv/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers==5.5.1->-r requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==2.41.1->-r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in ./.venv/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==2.41.1->-r requirements.txt (line 8)) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==2.41.1->-r requirements.txt (line 8)) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.28.1->google-genai==2.12.1->-r requirements.txt (line 10)) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.28.1->google-genai==2.12.1->-r requirements.txt (line 10)) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in ./.venv/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (2.1.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (3.0)
Requirement already satisfied: pyarrow>=21.0.0 in ./.venv/lib/python3.11/site-packages (from datasets>=4.7.0->trl==1.9.2->-r requirements.txt (line 7)) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in ./.venv/lib/python3.11/site-packages (from datasets>=4.7.0->trl==1.9.2->-r requirements.txt (line 7)) (0.4.1)

`data/knn_index/` is git-ignored, so the pool index is rebuilt each session. The register
centroid is committed and already present.

In [20]:
!python3 manage.py build_index --config configs/base_qwen.yaml

Embedding 10860 Persian/Arabic training sources with intfloat/multilingual-e5-large-instruct ...
Loading intfloat/multilingual-e5-large-instruct on device: cuda
Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 3424.69it/s]
Batches: 100%|███████████████████████████████| 340/340 [00:13<00:00, 25.26it/s]
Wrote index to data/knn_index/ : embeddings (10860, 1024), 10860 pairs

---
## Step 1 — the rarity list

In [21]:
!python3 manage.py rarity --config configs/sparse_retrieval.yaml

Counting term frequencies over 10860 training sources (zwnj=keep) ...
  22789 pool terms, 525 at df >= 40 -> 500 frozen (requested 500)
  2.2% of the vocabulary, realized df [40, 410]
  df histogram (frozen): {'1': 0, '2': 0, '3': 0, '4-9': 0, '10-99': 352, '100+': 148}
  ZWNJ variant collisions: 25 [('آسود\u200cگی', 'آسودگی'), ('الذین\u200cهم', 'الذینهم'), ('انشآء\u200cالله', 'انشآءالله')]
Wrote results/rarity_train.json and results/rarity_train_top50.tsv

In [22]:
import json

import pandas as pd

rarity = json.load(open('results/rarity_train.json'))
cfg = rarity['config']
print(f"{rarity['n_terms']} pool terms, {rarity['n_eligible']} at df >= {cfg['min_df']} "
      f"-> {rarity['n_frozen']} frozen (requested {cfg['freeze_n']})")
print(f"realized df {rarity['df_observed']}, {rarity['selected_frac']:.1%} of the vocabulary")
print('pool df histogram  :', rarity['df_histogram']['pool'])
print('frozen df histogram:', rarity['df_histogram']['frozen'])

# The list is the 500 rarest above the floor, so it stops wherever the 500th term sits:
# a ceiling on df is an outcome of the freeze, not a parameter.
print(f"n_eligible / freeze_n = {rarity['n_eligible'] / cfg['freeze_n']:.2f}; "
      f"at 1.0 the floor alone decides the list and the ranking selects nothing")

22789 pool terms, 525 at df >= 40 -> 500 frozen (requested 500)
realized df [40, 410], 2.2% of the vocabulary
pool df histogram  : {'1': 11668, '2': 3669, '3': 1809, '4-9': 3357, '10-99': 2113, '100+': 173}
frozen df histogram: {'1': 0, '2': 0, '3': 0, '4-9': 0, '10-99': 352, '100+': 148}
n_eligible / freeze_n = 1.05; at 1.0 the floor alone decides the list and the ranking selects nothing

In [23]:
# Terms tie in df in bulk, and ties fall to total frequency and then to token order.
# If the list concentrates on a few first letters, the token order is choosing it.
initials = pd.Series([t[0] for t, *_ in rarity['terms']]).value_counts()
print(f'{len(initials)} distinct first letters over {rarity["n_frozen"]} terms; '
      f'the top 5 hold {initials.head(5).sum() / rarity["n_frozen"]:.1%}')
initials.head(12).to_frame('terms').T

31 distinct first letters over 500 terms; the top 5 hold 56.4%

         ا   م   ب   ع   ن   ل   ت   ح   س   ک   و   ق
terms  135  43  42  35  27  21  15  15  14  14  13  13

In [24]:
# The check that matters: these should read as marked vocabulary. If the head is broken
# segmentation instead, the df count is ranking tokenizer debris — stop and fix it.
top = pd.read_csv('results/rarity_train_top50.tsv', sep='\t')
top['example'] = top['example'].str.slice(0, 60)
top

    rank      term  df  tf                                            example
0      0     احوال  40  40  و در ایّام و لیالی در سجن مذکور در اعمال و احو...
1      1     الأمم  40  40  إن الذین أوتوا بصائر من الله یَرَوْن حدود الله...
2      2     الاسم  40  40  اسألک بآیات عظمتک و ظهورات سلطنتک بأن تسخّر ال...
3      3       اما  40  40  و امّا العصمة الکبری لمن کان مقامه مقدّساً عن ...
4      4     امروز  40  40  یا شیخ امروز روز علوم و فنون ظاهره نبوده و نیس...
5      5    انفسهم  40  40  ای ربّ فألهمهم عجز انفسهم تلقآء مظهر نفسک و عل...
6      6     ایادی  40  40  سبحانک یا الهی هذا عبدک الّذی شرب خمر رحمتک من...
7      7     تالله  40  40  یا جلیل! وصّ العباد بتقوی الله. تالله! هو القا...
8      8      جاری  40  40  اشهد بأنّ امرک نافذ و حکمک جاری و مشیّتک ثابتة...
9      9  فردانیتک  40  40  انّک انت الّذی لم تزل کنت مقتدراً بمشیّتک و مر...
10    10      قرار  40  40  از قرار مذکور دولت ایران ایّدها الله هم اراده ...
11    11      نزلت  40  40  نزّلت صلاة تسع الرّکعات فی لوح منفصل توخّیاً ل...
12    12      ترقی  40  41  حکمت حکومت را شدّت سیاست دانست و مدار ترقّی سل...
13    13    سلطنتک  40  41  فأظهر فی الأرض سلطنتک و اقتدارک و علّم احبّتک ...
14    14       قلب  40  41  لمّا عرّفتنی هذا اسألک باسمک الّذی ما حمله الأ...
15    15       جهت  40  43  و در ایّام توقّف در سجن ارض طاء اگرچه نوم از ز...
16    16       عشر  40  47  حدّد حضرة بهاءالله سنّ البلوغ الشّرعی بخمسة عش...
17    17   الانشآء  41  41  اسألک یا مالک ممالک الانشآء و سلطان الأسمآء بأ...
18    18  المتعالی  41  41           انّک انت المقتدر المتعالی العزیز العظیم.
19    19      اکثر  41  41  یا الهی قد احاطت الظّلمة کلّ البلاد و بها اضطر...
20    20      بحیث  41  41  بحیث بلّغ الملوک جهرة رسالاتک و اوامرک و ما ار...
21    21       دین  41  41  الیوم دین الله و مذهب الله آنکه مذاهب مختلفه و...
22    22      سبقت  41  41  اسألک بآیاتک الّتی احاطت الممکنات و بنور وجهک ...
23    23     علیکم  41  41            قد حُرّم علیکم تقبیل الأیادی فی الکتاب.
24    24       لذا  41  41      لذا اخذوهم و فرّقوهم فی الأکناف اهل الاعتساف.
25    25    مملکتک  41  41  زیّن رأس البهآء بتاج الشّهادة فی سبیلک کما زیّ...
26    26    نداشته  41  41               این مظلوم خیال ریاست نداشته و ندارد.
27    27       نیر  41  41           کذلک کان نیّر الأمر من أفق العدل مشهوداً
28    28     القلم  41  42  یشیر القلم الأعلى إلى حضرة بهاءالله ویبیّن مقا...
29    29      شدند  41  42  مع آنکه در اکثری از بلاد ایران در این سنین اخی...
30    30      واقع  41  42  و بعد از توجّه حکایت حضرت سلطان ایّده الله تبا...
31    31     خواهد  41  44  و همچنین میفرماید اگر یک آیه از آیات من یظهره ...
32    32      أنتم  42  42                لا ونفسی الرحمن لو أنتم من المنصفین
33    33   الأحوال  42  42  اسألک ان تؤیّدنی فی کلّ الأحوال علی ذکرک و ثنا...
34    34     العرش  42  42  انّا نذکر لک الأمانة و مقامها عند الله ربّک رب...
35    35     الغیب  42  42  انّه اتی من سمآء الغیب و معه رایة یفعل ما یشآء...
36    36  الممکنات  42  42  اسألک بآیاتک الّتی احاطت الممکنات و بنور وجهک ...
37    37      اکبر  42  42  فاحفظ احبّتک من شرّهم ثمّ اجعلهم مستقیمین علی ...
38    38      باسم  42  42  و طوراً زیّنته باسم الرّوح و انزلته من سمآء مش...
39    39     بالحق  42  42  فسبحانک یا الهی ان لم ترحم عبادک فمن یرحمهم و ...
40    40     بسیار  42  42  ضغینه و بغضای مذهبی ناریست عالم‌سوز و اطفاء آن...
41    41      سحاب  42  42  اسألک بمظلومیّة نفسک و بابتلائها بین جنود الظّ...
42    42      محبت  42  42  بکمال محبّت و اتّحاد و مودّت و اتّفاق سلوک نما...
43    43    مواهبک  42  42    شجّعتنی مواهبک و الطافک و ظهورات فضلک و عنایتک.
44    44      کمال  42  42  مثل تو مثل آب تلخ صافیست که کمال لطافت و صفا ا...
45    45     بآنچه  42  43  از تو سؤال مینمایم این عبد را فائز فرمائی بآنچ...
46    46    تجعلنی  42  43  ای ربّ لا تحرمنی عن عرفانک فی ایّامک و لا تجعل...
47    47       شما  42  48  اگر نزد شما کلمه‌ئی و یا جوهریست که دون شما از...
48    48    الخبیر  43  43  ای ربّ لم ار لک ناصراً دونک و لا معیناً سواک. ...
49    49     اللوح  43  43  إشارة إلى تمجید حضرة الباب فی اللّوح الذی وجّه...

### Normalization check — ZWNJ

In [25]:
collisions = json.load(open('results/rarity_train.json'))['zwnj_collisions']
print(f'{len(collisions)} ZWNJ variant collisions')
pd.DataFrame(collisions, columns=['split spelling', 'joined spelling']).head(25)

25 ZWNJ variant collisions

   split spelling joined spelling
0         آسود‌گی          آسودگی
1        الذین‌هم         الذینهم
2      انشآء‌الله       انشآءالله
3         این‌قدر          اینقدر
4       بیچار‌گان        بیچارگان
5          بی‌خبر           بیخبر
6         بی‌مثال          بیمثال
7         جان‌فزا          جانفزا
8        خون‌ریزی         خونریزی
9         راست‌گو          راستگو
10      راه‌نمائی        راهنمائی
11        صد‌هزار          صدهزار
12        لا‌یزال          لایزال
13         مطا‌لب           مطالب
14        می‌توان          میتوان
15         می‌شود           میشود
16      می‌نمودند        مینمودند
17        می‌کنند          میکنند
18       نفوسی‌که         نفوسیکه
19        هم‌چنین          همچنین
20         هیچ‌یک           هیچیک
21         پست‌تر           پستتر
22     کمین‌گاهان       کمینگاهان
23      گم‌گشتگان        گمگشتگان
24        یکد‌یگر          یکدیگر

---
## Step 2 — leakage audit

In [26]:
!python manage.py leakage \
    --config configs/sparse_retrieval.yaml \
    --split val \
    --write-quarantine

Auditing 1323 val rows against 10860 pool rows ...
Loading intfloat/multilingual-e5-large-instruct on device: cuda
Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 3695.16it/s]
  17/1323 eval rows flagged, 22 pool rows implicated -> results/leakage_val.json
Quarantined 22 pool rows (0.20%) -> data/splits/pool_quarantine.json

In [27]:
leak = json.load(open('results/leakage_val.json'))
print(f"val: {leak['n_eval_rows_flagged']}/{leak['n_eval_rows']} eval rows flagged, "
      f"{leak['n_pool_rows_flagged']} pool rows implicated")
print('  max-cos histogram:', leak['max_cos_histogram'])

pd.DataFrame([
    {'cos': f['cos'], 'jac_src': f['jaccard_source'], 'jac_tgt': f['jaccard_target'],
     'eval': f['eval_source'][:50], 'pool': f['pool_source'][:50]}
    for f in leak['flags'][:10]
])

val: 17/1323 eval rows flagged, 22 pool rows implicated
  max-cos histogram: {'0.00-0.50': 0, '0.50-0.70': 0, '0.70-0.80': 0, '0.80-0.85': 0, '0.85-0.90': 506, '0.90-0.95': 816, '0.95-0.97': 1, '0.97-0.99': 0, '0.99-1.01': 0}

,cos,jac_src,jac_tgt,eval,pool
0,0.9508,0.7195,0.2353,امید هست در ظلّ سدرهٴ عنایت الهی تربیت شوید و ...,امید هست در ظلّ سدرهٔ عنایت الهیّه تربیت شوید ...
1,0.9451,0.8319,0.8779,چون که هر روز را امری و هر حین را حکمی مقتضی ل...,چون که هر روز را امری و هر حین را حکمتی مقتضی ...
2,0.9394,0.7059,0.6381,تمسّکوا بحبل الأسباب متوکّلین علی الله مسبّب ا...,تمسّکوا بحبل الأسباب متوکلین على الله مسبّب ال...
3,0.9331,0.7209,0.4286,انّک انت القویّ المقتدر العزیز المتین.,انّک انت المقتدر المتعالی القویّ العزیز العظیم.
4,0.9301,0.7313,0.8491,یا حزب الله مربّی عالم عدل است چه که دارای دو ...,مربّی عالم عدلست چه که دارای دو رکن است مجازات...
5,0.9298,0.5897,0.7500,ابغض النّاس عند الله من یقعد و یطلب.,أبغض الناس عند الله من یقعد ویطلب.
6,0.9267,0.9459,0.4831,انّک انت المقتدر العزیز المهیمن القیّوم.,و انّک انت المقتدر المهیمن العزیز القیّوم.
7,0.9251,0.8611,0.3600,و لا یسأل عمّا یفعل و کلّ عن کلّ یسألون.,انّه لا یسأل عمّا یفعل و کلّ عن کلّ یسألون.
8,0.9209,0.7308,0.7674,انّ ربّک لهو العلیم الحکیم.,انّ ربّک هو العلیم الحکیم.
9,0.9205,0.9048,0.5909,و الحمد لله ربّ العالمین.,الحمد لله ربّ العالمین!

In [28]:
!python3 manage.py build_index --config configs/base_qwen.yaml \
    --index_dir data/knn_index_clean \
    --quarantine data/splits/pool_quarantine.json

Quarantine data/splits/pool_quarantine.json: dropped 22 of 10860 rows
Embedding 10838 Persian/Arabic training sources with intfloat/multilingual-e5-large-instruct ...
Loading intfloat/multilingual-e5-large-instruct on device: cuda
Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 3516.13it/s]
Batches: 100%|███████████████████████████████| 339/339 [00:13<00:00, 26.06it/s]
Wrote index to data/knn_index_clean/ : embeddings (10838, 1024), 10838 pairs

---
## Step 3 — the sparse channel

The go/no-go. A query routes to the rare channel as soon as it carries one listed word,
so the numbers below are properties of the list: how many listed words a val query
carries, how often it carries any, and how often it carries four.

In [29]:
!python3 manage.py sparse_select --config configs/sparse_retrieval.yaml \
    --split val --index_dir data/knn_index

Selecting k=8 (up to m=4 rare) for 1323 val sources ...
Loading intfloat/multilingual-e5-large-instruct on device: cuda
Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 3281.25it/s]
Dense-only baseline for the redundancy comparison ...
  routes: {'full': 0.4255, 'partial': 0.483, 'dense': 0.0915}
  rare slots filled: mean 2.646, {'0': 121, '1': 208, '2': 252, '3': 179, '4': 563}
  queries with >= n rare terms: {'1': 0.9085, '2': 0.7513, '3': 0.5608, '4': 0.4255, '5': 0.2925, '6': 0.2003}
  targeted terms served: 1.0
  intra-set cosine: {'sparse': 0.8975, 'dense_baseline': 0.9001}
Wrote results/sparse_selection_val.json

In [30]:
sel = json.load(open('results/sparse_selection_val.json'))
print('routes            :', sel['route_fractions'])
print('rare words/query — mean', sel['query_terms']['mean'],
      'deciles', sel['query_terms']['deciles'])
print('share at or above :', sel['query_terms']['share_at_or_above'])
print('targeted served   :', sel['terms_served'])
print('rare slots filled :', sel['n_sparse']['histogram'])
print('intra-set cosine  :', sel['intra_set_similarity'])

routes            : {'full': 0.4255, 'partial': 0.483, 'dense': 0.0915}
rare words/query — mean 3.559 deciles [0, 1, 1, 2, 2, 3, 4, 4, 5, 8, 22]
share at or above : {'1': 0.9085, '2': 0.7513, '3': 0.5608, '4': 0.4255, '5': 0.2925, '6': 0.2003}
targeted served   : 1.0
rare slots filled : {'0': 121, '1': 208, '2': 252, '3': 179, '4': 563}
intra-set cosine  : {'sparse': 0.8975, 'dense_baseline': 0.9001}

In [31]:
# One exemplar per selected word, so a query carrying four listed words fills four slots:
# the full-dose rate should track the share carrying four, unlike under greedy coverage.
EXPECTED = {'mean matches/query': 3.0, '>=1 match': 0.88, 'full dose (4 slots)': 0.34}
FULL_DOSE_GATE = 0.30

now = {
    'mean matches/query': sel['query_terms']['mean'],
    '>=1 match': sel['query_terms']['share_at_or_above']['1'],
    'full dose (4 slots)': sel['route_fractions']['full'],
}
print(pd.DataFrame({'now': now, 'expected': EXPECTED}).to_string())

gap = sel['query_terms']['share_at_or_above']['4'] - now['full dose (4 slots)']
print(f"\nqueries carrying 4+ listed words that did not fill 4 slots: {gap:.1%} "
      f"(every pool example carrying the word was already taken)")

full = now['full dose (4 slots)']
verdict = 'PROCEED' if full >= FULL_DOSE_GATE else 'HOLD'
print(f'full dose {full:.1%} against a {FULL_DOSE_GATE:.0%} gate -> {verdict}')
if verdict == 'HOLD':
    print('Report these numbers; do not generate on this list.')

                        now  expected
mean matches/query   3.5590      3.00
>=1 match            0.9085      0.88
full dose (4 slots)  0.4255      0.34

queries carrying 4+ listed words that did not fill 4 slots: 0.0% (every pool example carrying the word was already taken)
full dose 42.5% against a 30% gate -> PROCEED

In [32]:
import numpy as np
import yaml

from src.retrieval.rarity import load_irregular
from src.retrieval.retrieve import RetrievalIndex
from src.retrieval.sparse import SparseRetriever

# Rare picks ran 15.4% shorter than the baseline's exemplars on the old list. A rare arm
# whose prompts are systematically shorter confounds quality with prompt length.
CFG = yaml.safe_load(open('configs/sparse_retrieval.yaml'))
RETR, SPA, RAR = CFG['retrieval'], CFG['sparse'], CFG['rarity']
SRC = [json.loads(ln)['input'] for ln in open('data/splits/val.jsonl') if ln.strip()]

index = RetrievalIndex('data/knn_index_clean', embed_model=RETR['embed_model'])
retriever = SparseRetriever(
    index, load_irregular(RAR['out']), index, zwnj=RAR['zwnj'], m=SPA['m'],
)
SELECTED, TRACES = retriever.select_with_trace(SRC, k=RETR['k'])
BASE_SEL = index.retrieve(SRC, k=RETR['k'])

RAR_LEN, COS_LEN = [], []
for t in TRACES:
    rows = set(t['sparse_rows'])
    for r in t['final_rows']:
        (RAR_LEN if r in rows else COS_LEN).append(len(index.pairs[r]['input']))

BASE_CHARS = sum(len(e['input']) for row in BASE_SEL for e in row) / len(TRACES)
ARM_CHARS = (sum(RAR_LEN) + sum(COS_LEN)) / len(TRACES)
for name, v in (('query', [len(x) for x in SRC]), ('rare channel', RAR_LEN),
                ('cosine fill', COS_LEN)):
    a = np.array(v)
    print(f'{name:14s} n={len(a):6d}  mean {a.mean():6.1f}  median {np.median(a):6.1f} chars')
print(f'exemplar chars per prompt: dense {BASE_CHARS:.0f} -> sparse {ARM_CHARS:.0f} '
      f'({ARM_CHARS / BASE_CHARS - 1:+.1%})')

Loading intfloat/multilingual-e5-large-instruct on device: cuda

Loading weights: 100%|██████████| 391/391 [00:00<00:00, 3144.51it/s]

query          n=  1323  mean   78.2  median   63.0 chars
rare channel   n=  3501  mean  197.3  median  175.0 chars
cosine fill    n=  7083  mean  199.0  median  181.0 chars
exemplar chars per prompt: dense 1606 -> sparse 1587 (-1.2%)

In [33]:
for min_df in (1, 10, 30, 60):
    lst = f'results/rarity_train_mindf{min_df}.json'
    print(f'--- min_df={min_df}')
    !python3 manage.py rarity --config configs/sparse_retrieval.yaml --min_df {min_df} --out {lst} 2>&1 | grep -E 'frozen|realized'
    !python3 manage.py sparse_select --config configs/sparse_retrieval.yaml --split val --index_dir data/knn_index_clean --rarity {lst} --out results/sparse_sweep_val_mindf{min_df}.json 2>&1 | grep -E 'routes|rare slots'

--- min_df=1
  22789 pool terms, 22789 at df >= 1 -> 500 frozen (requested 500)
  2.2% of the vocabulary, realized df [1, 1]
  df histogram (frozen): {'1': 500, '2': 0, '3': 0, '4-9': 0, '10-99': 0, '100+': 0}
  routes: {'full': 0.0, 'partial': 0.0144, 'dense': 0.9856}
  rare slots filled: mean 0.014, {'0': 1304, '1': 19, '2': 0, '3': 0, '4': 0}
--- min_df=10
  22789 pool terms, 2286 at df >= 10 -> 500 frozen (requested 500)
  2.2% of the vocabulary, realized df [10, 12]
  df histogram (frozen): {'1': 0, '2': 0, '3': 0, '4-9': 0, '10-99': 500, '100+': 0}
  routes: {'full': 0.003, 'partial': 0.2955, 'dense': 0.7014}
  rare slots filled: mean 0.392, {'0': 928, '1': 294, '2': 82, '3': 15, '4': 4}
--- min_df=30
  22789 pool terms, 718 at df >= 30 -> 500 frozen (requested 500)
  2.2% of the vocabulary, realized df [30, 79]
  df histogram (frozen): {'1': 0, '2': 0, '3': 0, '4-9': 0, '10-99': 500, '100+': 0}
  routes: {'full': 0.1308, 'partial': 0.5896, 'dense': 0.2797}
  rare slots filled: mean 1.514, {'0': 370, '1': 391, '2': 247, '3': 142, '4': 173}
--- min_df=60
  22789 pool terms, 311 at df >= 60 -> 311 frozen (requested 500)
  1.4% of the vocabulary, realized df [60, 6805]
  df histogram (frozen): {'1': 0, '2': 0, '3': 0, '4-9': 0, '10-99': 138, '100+': 173}
  routes: {'full': 0.7241, 'partial': 0.2547, 'dense': 0.0212}
  rare slots filled: mean 3.454, {'0': 28, '1': 77, '2': 120, '3': 140, '4': 958}

In [34]:
for ex in sel['examples']:
    print('QUERY :', ex['source'][:90])
    print('  route', ex['trace']['route'], '| carries', ex['trace']['query_terms'])
    print('  served', ex['trace']['served_terms'], f"+ {ex['trace']['n_knn']} kNN")
    for e in ex['exemplars']:
        print('   -', e[:90])
    print()

QUERY : جواهر الأسرار فی معارج الأسفار لمن اراد ان یتقرّب بالله المقتدر الغفّار فهنیاً للأبرار الّ
  route full | carries ['اراد', 'بالله', 'هذه', 'لمن', 'المقتدر', 'الذین']
  served ['اراد', 'بالله', 'هذه', 'لمن'] + 4 kNN
   - و بهدایت کبری و ربوبیّت عظمی مبعوث شوند که تا قلوب مشتاقین و حقایق صافین را بالهامات غیبیّ
   - فأمطر من سحاب فیض فضلک ما تطهّر به افئدة عبادک عمّا یحجبهم عن النّظر الی وجهک و یمنعهم عن
   - اللّهمّ انّی اسألک بالحرف الّتی اذا خرجت من فم مشیّتک ماجت البحار و هاجت الأریاح و ظهرت ال
   - من شرب من الکأس الّتی تدور بها ید رحمتک ینقطع عن دونک و ینجذب بکلمة منه عبادک الّذین رقدوا
   - طوبی لمن فاز بلقائک و شرب رحیق الوصال من ایادی عطائک و وجد عرف آیاتک و نطق بثنائک و طار فی
   - اسألک بضجیج المشتاقین فی هجرک و صریخ العاشقین فی بعدهم عن لقائک بأن ترزقنی خمر عرفانک و کو
   - تفکّروا فی هذه الآیة ثم انصفوا بالله لعلّ تجدون لئالئ الأسرار من البحر الذی تموّج باسمی ال
   - لو تسمع صریر القلم الأعلی و هدیر ورقآء البقآء علی افنان سدرة المنتهی فی ذکر الله موجد الأس

QUERY : هو العلیّ الأعلی.
  route partial | carries ['العلی', 'الأعلی', 'هو']
  served ['العلی', 'الأعلی', 'هو'] + 5 kNN
   - لا اله الّا هو المتعالی الأمنع الأقدس الأرفع الأعزّ الأجلّ الأکرم العلیم الخبیر.
   - لا اله الّا هو العلیّ، الأعلی.
   - لا اله الّا هو العزیز المقتدر المتعالی العلیم المحیط البصیر الخبیر المهیمن النّوّار.
   - لا اله الّا انت العلیّ الأعلی.
   - لا اله الّا انت المقتدر العلیّ الأعلی.
   - لا اله الّا هو الفرد الواحد المقتدر العلیم الحکیم.
   - انّه لا اله الّا هو العالم المقتدر المهیمن العزیز الحمید.
   - و انّک انت ربّ البهآء و محبوب البهآء و المذکور فی قلب البهآء و النّاطق بلسان البهآء و المس

QUERY : یا ایّها السّالک فی سبل العدل و النّاظر الی طلعة الفضل.
  route partial | carries ['الفضل', 'ایها', 'العدل']
  served ['الفضل', 'ایها', 'العدل'] + 5 kNN
   - یدعوک البهآء و یسألک بأنوار وجهک و امواج بحر امرک و تجلّیات شمس بیانک ان تؤیّد السّلطان عل
   - و لوجه الصّدق جمالاً و لهیکل الأمانة طرازاً و لبیت الأخلاق عرشاً و لجسد العالم روحاً و لجن
   - فلک الحمد یا الهی علی ما قضیت بسلطان قضائک و تقضی بتقدیرک و امضائک. اسئلک یا محبوبی باسمک
   - انّا وصّینا اولیائنا بتقوی الله، الّذی کان مطلع الأعمال و الأخلاق. انّه قائد جنود العدل فی
   - ثمّ، اقبلنا الی الیسار شاهدنا طلعة من طلعات الفردوس الأعلی قائمة علی عمود من النّور و نادت
   - اسألک یا مالک الأسمآء و فاطر السّمآء ان تؤیّدهم علی الانصاف فی امرک لعلّ یجدون عرف قمیص رح
   - یا ایّها العادل علی من فی السّموات و الأرض و یا ایّها الحاکم علی من فی ملکوت الأمر و الخلق
   - نطقت و انطق امام الوجوه قد فتح باب الفضل و اتی مطلع العدل بآیات واضحات و حجج باهرات من لدی