# Rarity-driven sparse retrieval — diagnostics

| Section | What runs | Gate |
|---|---|---|
| Step 1 | `rarity` — IDF over the pool, irregular-term list | terms are scriptural vocabulary, not tokenizer debris |
| Step 3 | `leakage` — near-duplicate audit, quarantine | flag count small enough that quarantining leaves the pool intact |
| Step 2 | `sparse_select` — greedy coverage dry run | the channel fires often enough, and is less redundant than dense |

In [1]:
# e5-large in fp32 over a 10.8k-row pool; any Colab GPU is enough.
!nvidia-smi --query-gpu=name,memory.total --format=csv

name, memory.total [MiB]
NVIDIA GeForce RTX 4060 Laptop GPU, 8188 MiB

In [2]:
%cd /home/prnamhr/projects/Style-Aware-MT
!pip install -r requirements.txt

# Text-only pipeline; these two carry an ABI mismatch against the pinned torch.
!pip uninstall -y torchvision torchaudio

/home/prnamhr/projects/Style-Aware-MT

Requirement already satisfied: sentence-transformers==5.5.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (5.5.1)
Requirement already satisfied: torch==2.12.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (2.12.0)
Requirement already satisfied: transformers==5.12.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (5.12.1)
Requirement already satisfied: accelerate==1.14.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: bitsandbytes==0.49.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (0.49.2)
Requirement already satisfied: peft==0.18.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (0.18.0)
Requirement already satisfied: trl==1.9.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (1.9.2)
Requirement already satisfied: openai==2.41.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (2.41.1)
Requirement already satisfied: anthropic==0.109.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (0.109.1)
Requirement already satisfied: google-genai==2.12.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (2.12.1)
Requirement already satisfied: sacrebleu==2.6.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (2.6.0)
Requirement already satisfied: matplotlib==3.11.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (3.11.1)
Requirement already satisfied: PyYAML==6.0.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 13)) (6.0.3)
Requirement already satisfied: python-dotenv==1.2.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 14)) (1.2.2)
Requirement already satisfied: asttokens==3.0.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (3.0.1)
Requirement already satisfied: comm==0.2.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 16)) (0.2.3)
Requirement already satisfied: debugpy==1.8.19 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 17)) (1.8.19)
Requirement already satisfied: decorator==5.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 18)) (5.2.1)
Requirement already satisfied: executing==2.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 19)) (2.2.1)
Requirement already satisfied: ipykernel==7.1.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 20)) (7.1.0)
Requirement already satisfied: ipython==9.9.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 21)) (9.9.0)
Requirement already satisfied: ipython_pygments_lexers==1.1.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 22)) (1.1.1)
Requirement already satisfied: jedi==0.19.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 23)) (0.19.2)
Requirement already satisfied: joblib==1.5.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 24)) (1.5.3)
Requirement already satisfied: jupyter_client==8.8.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 25)) (8.8.0)
Requirement already satisfied: jupyter_core==5.9.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 26)) (5.9.1)
Requirement already satisfied: lxml==6.0.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 27)) (6.0.2)
Requirement already satisfied: matplotlib-inline==0.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 28)) (0.2.1)
Requirement already satisfied: nest-asyncio==1.6.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 29)) (1.6.0)
Requirement already satisfied: numpy==2.4.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 30)) (2.4.1)
Requirement already satisfied: packaging==25.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 31)) (25.0)
Requirement already satisfied: pandas==2.3.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 32)) (2.3.3)
Requirement already satisfied: parso==0.8.5 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 33)) (0.8.5)
Requirement already satisfied: pexpect==4.9.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 34)) (4.9.0)
Requirement already satisfied: platformdirs==4.5.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 35)) (4.5.1)
Requirement already satisfied: prompt_toolkit==3.0.52 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 36)) (3.0.52)
Requirement already satisfied: psutil==7.2.1 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 37)) (7.2.1)
Requirement already satisfied: ptyprocess==0.7.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 38)) (0.7.0)
Requirement already satisfied: pure_eval==0.2.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 39)) (0.2.3)
Requirement already satisfied: Pygments==2.19.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 40)) (2.19.2)
Requirement already satisfied: python-dateutil==2.9.0.post0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 41)) (2.9.0.post0)
Requirement already satisfied: python-docx==1.2.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 42)) (1.2.0)
Requirement already satisfied: pytz==2025.2 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 43)) (2025.2)
Requirement already satisfied: pyzmq==27.1.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 44)) (27.1.0)
Requirement already satisfied: scikit-learn==1.8.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 45)) (1.8.0)
Requirement already satisfied: scipy==1.17.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 46)) (1.17.0)
Requirement already satisfied: six==1.17.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 47)) (1.17.0)
Requirement already satisfied: stack-data==0.6.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 48)) (0.6.3)
Requirement already satisfied: threadpoolctl==3.6.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 49)) (3.6.0)
Requirement already satisfied: tornado==6.5.4 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 50)) (6.5.4)
Requirement already satisfied: traitlets==5.14.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 51)) (5.14.3)
Requirement already satisfied: typing_extensions==4.15.0 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 52)) (4.15.0)
Requirement already satisfied: tzdata==2025.3 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 53)) (2025.3)
Requirement already satisfied: wcwidth==0.2.14 in ./.venv/lib/python3.11/site-packages (from -r requirements.txt (line 54)) (0.2.14)
Requirement already satisfied: huggingface-hub>=0.23.0 in ./.venv/lib/python3.11/site-packages (from sentence-transformers==5.5.1->-r requirements.txt (line 1)) (1.28.0)
Requirement already satisfied: tqdm>=4.0.0 in ./.venv/lib/python3.11/site-packages (from sentence-transformers==5.5.1->-r requirements.txt (line 1)) (4.68.3)
Requirement already satisfied: regex>=2025.10.22 in ./.venv/lib/python3.11/site-packages (from transformers==5.12.1->-r requirements.txt (line 3)) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in ./.venv/lib/python3.11/site-packages (from transformers==5.12.1->-r requirements.txt (line 3)) (0.22.2)
Requirement already satisfied: typer in ./.venv/lib/python3.11/site-packages (from transformers==5.12.1->-r requirements.txt (line 3)) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in ./.venv/lib/python3.11/site-packages (from transformers==5.12.1->-r requirements.txt (line 3)) (0.8.0)
Requirement already satisfied: filelock in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.29.5)
Requirement already satisfied: setuptools<82 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (79.0.1)
Requirement already satisfied: sympy>=1.13.3 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.6.1)
Requirement already satisfied: jinja2 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (2026.6.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.2)
Requirement already satisfied: nvidia-cublas<=13.1.1.3,>=13.1.0.3 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (13.1.1.3)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.4.5)
Requirement already satisfied: triton==3.7.0 in ./.venv/lib/python3.11/site-packages (from torch==2.12.0->-r requirements.txt (line 2)) (3.7.0)
Requirement already satisfied: datasets>=4.7.0 in ./.venv/lib/python3.11/site-packages (from trl==1.9.2->-r requirements.txt (line 7)) (5.0.1)
Requirement already satisfied: anyio<5,>=3.5.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (4.14.1)
Requirement already satisfied: distro<2,>=1.7.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (0.28.1)
Requirement already satisfied: jiter<1,>=0.10.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (0.16.0)
Requirement already satisfied: pydantic<3,>=1.9.0 in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (2.13.4)
Requirement already satisfied: sniffio in ./.venv/lib/python3.11/site-packages (from openai==2.41.1->-r requirements.txt (line 8)) (1.3.1)
Requirement already satisfied: docstring-parser<1,>=0.15 in ./.venv/lib/python3.11/site-packages (from anthropic==0.109.1->-r requirements.txt (line 9)) (0.18.0)
Requirement already satisfied: google-auth<2.56.0,>=2.48.1 in ./.venv/lib/python3.11/site-packages (from google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (2.55.2)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in ./.venv/lib/python3.11/site-packages (from google-genai==2.12.1->-r requirements.txt (line 10)) (2.34.2)
Requirement already satisfied: tenacity<9.2.0,>=8.2.3 in ./.venv/lib/python3.11/site-packages (from google-genai==2.12.1->-r requirements.txt (line 10)) (9.1.4)
Requirement already satisfied: websockets<17.0,>=13.0.0 in ./.venv/lib/python3.11/site-packages (from google-genai==2.12.1->-r requirements.txt (line 10)) (16.1.1)
Requirement already satisfied: portalocker in ./.venv/lib/python3.11/site-packages (from sacrebleu==2.6.0->-r requirements.txt (line 11)) (3.2.0)
Requirement already satisfied: tabulate>=0.8.9 in ./.venv/lib/python3.11/site-packages (from sacrebleu==2.6.0->-r requirements.txt (line 11)) (0.10.0)
Requirement already satisfied: colorama in ./.venv/lib/python3.11/site-packages (from sacrebleu==2.6.0->-r requirements.txt (line 11)) (0.4.6)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (1.5.0)
Requirement already satisfied: pillow>=9 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (12.3.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.11/site-packages (from matplotlib==3.11.1->-r requirements.txt (line 12)) (3.3.2)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in ./.venv/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.0->-r requirements.txt (line 2)) (13.0.85)
Requirement already satisfied: idna>=2.8 in ./.venv/lib/python3.11/site-packages (from anyio<5,>=3.5.0->openai==2.41.1->-r requirements.txt (line 8)) (3.18)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in ./.venv/lib/python3.11/site-packages (from cuda-bindings<14,>=13.0.3->torch==2.12.0->-r requirements.txt (line 2)) (1.5.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in ./.venv/lib/python3.11/site-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in ./.venv/lib/python3.11/site-packages (from google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (49.0.0)
Requirement already satisfied: certifi in ./.venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai==2.41.1->-r requirements.txt (line 8)) (2026.6.17)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.11/site-packages (from httpx<1,>=0.23.0->openai==2.41.1->-r requirements.txt (line 8)) (1.0.9)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai==2.41.1->-r requirements.txt (line 8)) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in ./.venv/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers==5.5.1->-r requirements.txt (line 1)) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in ./.venv/lib/python3.11/site-packages (from huggingface-hub>=0.23.0->sentence-transformers==5.5.1->-r requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==2.41.1->-r requirements.txt (line 8)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in ./.venv/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==2.41.1->-r requirements.txt (line 8)) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in ./.venv/lib/python3.11/site-packages (from pydantic<3,>=1.9.0->openai==2.41.1->-r requirements.txt (line 8)) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.28.1->google-genai==2.12.1->-r requirements.txt (line 10)) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in ./.venv/lib/python3.11/site-packages (from requests<3.0.0,>=2.28.1->google-genai==2.12.1->-r requirements.txt (line 10)) (2.7.0)
Requirement already satisfied: cffi>=2.0.0 in ./.venv/lib/python3.11/site-packages (from cryptography>=38.0.3->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (2.1.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.11/site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<2.56.0,>=2.48.1->google-auth[requests]<2.56.0,>=2.48.1->google-genai==2.12.1->-r requirements.txt (line 10)) (3.0)
Requirement already satisfied: pyarrow>=21.0.0 in ./.venv/lib/python3.11/site-packages (from datasets>=4.7.0->trl==1.9.2->-r requirements.txt (line 7)) (25.0.0)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in ./.venv/lib/python3.11/site-packages (from datasets>=4.7.0->trl==1.9.2->-r requirements.txt (line 7)) (0.4.1)

`data/knn_index/` is git-ignored, so the pool index is rebuilt each session. The register
centroid is committed and already present.

In [3]:
!python3 manage.py build_index --config configs/base_qwen.yaml

Embedding 10860 Persian/Arabic training sources with intfloat/multilingual-e5-large-instruct ...
Loading intfloat/multilingual-e5-large-instruct on device: cuda
Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 3439.48it/s]
Batches: 100%|███████████████████████████████| 340/340 [00:13<00:00, 25.34it/s]
Wrote index to data/knn_index/ : embeddings (10860, 1024), 10860 pairs

---
## Step 1 — the rarity list

In [4]:
!python3 manage.py rarity --config configs/sparse_retrieval.yaml

Computing IDF over 10860 pool sources (zwnj=keep) ...
  22789 pool terms, 11121 at df >= 2 -> 500 frozen (requested 500)
  2.2% of the vocabulary, realized df [2, 2]
  df histogram (frozen): {'1': 0, '2': 500, '3': 0, '4-9': 0, '10-99': 0, '100+': 0}
  ZWNJ variant collisions: 25 [('آسود\u200cگی', 'آسودگی'), ('الذین\u200cهم', 'الذینهم'), ('انشآء\u200cالله', 'انشآءالله')]
Wrote results/rarity_train.json and results/rarity_train_sample50.tsv

In [5]:
import json

import pandas as pd

rarity = json.load(open('results/rarity_train.json'))
cfg = rarity['config']
print(f"{rarity['n_terms']} pool terms, {rarity['n_eligible']} at df >= {cfg['min_df']} "
      f"-> {rarity['n_frozen']} frozen (requested {cfg['freeze_n']})")
print(f"realized df {rarity['df_observed']}, {rarity['selected_frac']:.1%} of the vocabulary")
print('pool df histogram  :', rarity['df_histogram']['pool'])
print('frozen df histogram:', rarity['df_histogram']['frozen'])

sample = pd.read_csv('results/rarity_train_sample50.tsv', sep='\t')
sample['example'] = sample['example'].str.slice(0, 60)
sample

22789 pool terms, 11121 at df >= 2 -> 500 frozen (requested 500)
realized df [2, 2], 2.2% of the vocabulary
pool df histogram  : {'1': 11668, '2': 3669, '3': 1809, '4-9': 3357, '10-99': 2113, '100+': 173}
frozen df histogram: {'1': 0, '2': 500, '3': 0, '4-9': 0, '10-99': 0, '100+': 0}

        term     idf  df                                            example
0   آفریدگان  9.1943   2  پس گوهر پاک مردمرا از میان آفریدگان برگزید و ا...
1       أبرز  9.1943   2  وعلاوة على مواصلة حضرة ولی أمرالله شرح أهمیة ا...
2       أخیه  9.1943   2  کما وصفه حضرة الباب فی کتاب قیّوم الأسماء بأنّ...
3     أداؤها  9.1943   2  أمّا إذا حلّ وقت الصلاة وکان المسافر مستریحا و...
4       أذکر  9.1943   2  أذکر من کان أعظم منک شأناً وأکبر منک مقاماً أی...
5    أمرناکم  9.1943   2  إنا أمرناکم بکسر حدودات النفس والهوى لا ما رقم...
6     أنزلها  9.1943   2  اشتملت بعض الألواح المبارکة التی أنزلها حضرة ب...
7      اتابک  9.1943   2  میرزا تقی خان امیرنظام وزیر اعظم و اتابک معظّم...
8      اثرها  9.1943   2  فانّها حین طلوعها عن افقها تکون حرارتها و اثره...
9      اثنای  9.1943   2  و خود باب اهمّیّتی باین شور و آشوب نداده در نه...
10     اجساد  9.1943   2  لک ان تنطق الیوم بما تشتعل به الأفئدة و تطیر ا...
11   احتجبوا  9.1943   2  و الّذین احتجبوا ظنّوا بأنّهم مطفئ نورک و مخمد...
12     احراق  9.1943   2  و یا خود بجهت آنکه در شام عیش مهیّا و سفرهٔ مه...
13     احمدی  9.1943   2  احمدی ربّک قد کنت محترقة بنار الفراق اذاً ماج ...
14     اخترت  9.1943   2  فلمّا اردت ان تعرف فخلقت العالم الاکبر و الاصغ...
15    اختصصت  9.1943   2  و به طرّزت دیباج کتاب اوامرک بین بریّتک و زیّن...
16    ادبیات  9.1943   2  چنانچه موٴلّف محقّق مشهور دریبار از اهالی فران...
17    اذکروه  9.1943   2  خرّوا بوجوهکم سجّداً لله ثمّ اذکروه فی آنآء ال...
18  ارسلناها  9.1943   2  هذه آیات انزلناها من قبل فی اوّل ورودنا فی سجن...
19   اریاحها  9.1943   2                   و من هزیز اریاحها قد اتی المالک.
20    استشهد  9.1943   2  و انت تعلم یا الهی لم یکن فی ارضک من ینسب الیک...
21   استعلآء  9.1943   2  فأرسل یا الهی علی احبّتی ما تفرح به قلوبهم و ت...
22   استفسار  9.1943   2  ایکاش حضرت پادشاه ممالک ایران ادام الله سلطانه...
23   اسرائیل  9.1943   2  قوله فاستعدّ للقآء الهک یا اسرائیل فانّه هو ذا...
24     اسلحه  9.1943   2  از جمله ذکر نمود حضرات اسلحه جمع کرده‌اند و بع...
25      اسکن  9.1943   2                      و انا أقول: ان اصبر ثمّ اسکن.
26    اشعاری  9.1943   2  یشهد لسان سرّی و جهری و اعضائی و جوارحی و عروق...
27    اصلیهٴ  9.1943   2  ولکن مقصود صعود انفس طیّبه و جواهر مجرّده است ...
28    اطمئنی  9.1943   2                                 اطمئنّی بفضل ربّک.
29  اعترافهم  9.1943   2  بل انّه یری نفسه اخجل منهم عند اعترافهم بما فا...
30     افغان  9.1943   2  مرا چنان گمان بود که حضرت اتابک مرا مأمور بحرب...
31      اقتل  9.1943   2  اشهد یا الهی لو اقتل فی سبیلک فی کلّ حین الف م...
32   الآیتین  9.1943   2  إذا أرید الطلاق بعد تلاوة الآیتین ودفع المهر، ...
33    الأرفع  9.1943   2  لو یطّلع احد علی ما قدّر له فی عوالم الله ربّ ...
34   الأساسی  9.1943   2  وأنّ الهدف الأساسیّ، عند ثبوت هذا الجرم وفرض ا...
35    الألسن  9.1943   2  تری ما ورد علی المظلوم من الّذین ما عاشرونی و ...
36   الأنهار  9.1943   2  و اسألک یا الهی باسمک الّذی به امطرت السّحاب و...
37   الأولیة  9.1943   2  و کبّر اللّهمّ یا الهی علی النّقطة الأوّلیّة و...
38   الإنصاف  9.1943   2  لعمری من شرب رحیق الإنصاف من أیادی الألطاف إنه...
39  الاختلاف  9.1943   2          الرّجوع إلى النصوص المبارکة عند الاختلاف.
40   الاریاح  9.1943   2  قد اخذتنی حرارة حبّک و سکر رحیق توحیدک علی مقا...
41    البارد  9.1943   2  الحُکم واحد فی الحالین، ویُرجّح الماء الفاتر، ...
42     البدن  9.1943   2     طوبی لروح خرج من البدن مقدّساً عن شبهات الأمم.
43  البشارات  9.1943   2  وذکر حضرة بهاءالله فی لوح البشارات أنّ مثل هذا...
44    البشری  9.1943   2  اختیار لسان واحد وانتخاب خطّ عمومی لاستعمال أه...
45    البقاء  9.1943   2  یا ملوک أمریقا ورؤساء الجمهور فیها اسمعوا ما ت...
46    البنآء  9.1943   2     کذلک ینبئک النّبأ الأعظم من هذا البنآء العظیم.
47   التجارة  9.1943   2  فاعلموا بأنّ البلایا و المحن لم یزل کانت موکّل...
48   الحالین  9.1943   2  الحُکم واحد فی الحالین، ویُرجّح الماء الفاتر، ...
49     الحان  9.1943   2  مثلاً عالم ربّانی اگر در محاورهٔ با شخص مسیحی ...

### Normalization check — ZWNJ

In [6]:
collisions = json.load(open('results/rarity_train.json'))['zwnj_collisions']
print(f'{len(collisions)} ZWNJ variant collisions')
pd.DataFrame(collisions, columns=['split spelling', 'joined spelling']).head(25)

25 ZWNJ variant collisions

   split spelling joined spelling
0         آسود‌گی          آسودگی
1        الذین‌هم         الذینهم
2      انشآء‌الله       انشآءالله
3         این‌قدر          اینقدر
4       بیچار‌گان        بیچارگان
5          بی‌خبر           بیخبر
6         بی‌مثال          بیمثال
7         جان‌فزا          جانفزا
8        خون‌ریزی         خونریزی
9         راست‌گو          راستگو
10      راه‌نمائی        راهنمائی
11        صد‌هزار          صدهزار
12        لا‌یزال          لایزال
13         مطا‌لب           مطالب
14        می‌توان          میتوان
15         می‌شود           میشود
16      می‌نمودند        مینمودند
17        می‌کنند          میکنند
18       نفوسی‌که         نفوسیکه
19        هم‌چنین          همچنین
20         هیچ‌یک           هیچیک
21         پست‌تر           پستتر
22     کمین‌گاهان       کمینگاهان
23      گم‌گشتگان        گمگشتگان
24        یکد‌یگر          یکدیگر

---
## Step 3 — leakage audit

In [7]:
!python manage.py leakage \
    --config configs/sparse_retrieval.yaml \
    --split val \
    --write-quarantine

Auditing 1323 val rows against 10860 pool rows ...
Loading intfloat/multilingual-e5-large-instruct on device: cuda
Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 3310.87it/s]
  17/1323 eval rows flagged, 22 pool rows implicated -> results/leakage_val.json
Quarantined 22 pool rows (0.20%) -> data/splits/pool_quarantine.json

In [8]:
leak = json.load(open('results/leakage_val.json'))
print(f"val: {leak['n_eval_rows_flagged']}/{leak['n_eval_rows']} eval rows flagged, "
      f"{leak['n_pool_rows_flagged']} pool rows implicated")
print('  max-cos histogram:', leak['max_cos_histogram'])

pd.DataFrame([
    {'cos': f['cos'], 'jac_src': f['jaccard_source'], 'jac_tgt': f['jaccard_target'],
     'eval': f['eval_source'][:50], 'pool': f['pool_source'][:50]}
    for f in leak['flags'][:10]
])

val: 17/1323 eval rows flagged, 22 pool rows implicated
  max-cos histogram: {'0.00-0.50': 0, '0.50-0.70': 0, '0.70-0.80': 0, '0.80-0.85': 0, '0.85-0.90': 506, '0.90-0.95': 816, '0.95-0.97': 1, '0.97-0.99': 0, '0.99-1.01': 0}

,cos,jac_src,jac_tgt,eval,pool
0,0.9508,0.7195,0.2353,امید هست در ظلّ سدرهٴ عنایت الهی تربیت شوید و ...,امید هست در ظلّ سدرهٔ عنایت الهیّه تربیت شوید ...
1,0.9451,0.8319,0.8779,چون که هر روز را امری و هر حین را حکمی مقتضی ل...,چون که هر روز را امری و هر حین را حکمتی مقتضی ...
2,0.9394,0.7059,0.6381,تمسّکوا بحبل الأسباب متوکّلین علی الله مسبّب ا...,تمسّکوا بحبل الأسباب متوکلین على الله مسبّب ال...
3,0.9331,0.7209,0.4286,انّک انت القویّ المقتدر العزیز المتین.,انّک انت المقتدر المتعالی القویّ العزیز العظیم.
4,0.9301,0.7313,0.8491,یا حزب الله مربّی عالم عدل است چه که دارای دو ...,مربّی عالم عدلست چه که دارای دو رکن است مجازات...
5,0.9298,0.5897,0.7500,ابغض النّاس عند الله من یقعد و یطلب.,أبغض الناس عند الله من یقعد ویطلب.
6,0.9267,0.9459,0.4831,انّک انت المقتدر العزیز المهیمن القیّوم.,و انّک انت المقتدر المهیمن العزیز القیّوم.
7,0.9251,0.8611,0.3600,و لا یسأل عمّا یفعل و کلّ عن کلّ یسألون.,انّه لا یسأل عمّا یفعل و کلّ عن کلّ یسألون.
8,0.9209,0.7308,0.7674,انّ ربّک لهو العلیم الحکیم.,انّ ربّک هو العلیم الحکیم.
9,0.9205,0.9048,0.5909,و الحمد لله ربّ العالمین.,الحمد لله ربّ العالمین!

In [9]:
!python3 manage.py build_index --config configs/base_qwen.yaml \
    --index_dir data/knn_index_clean \
    --quarantine data/splits/pool_quarantine.json

Quarantine data/splits/pool_quarantine.json: dropped 22 of 10860 rows
Embedding 10838 Persian/Arabic training sources with intfloat/multilingual-e5-large-instruct ...
Loading intfloat/multilingual-e5-large-instruct on device: cuda
Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 3507.85it/s]
Batches: 100%|███████████████████████████████| 339/339 [00:13<00:00, 25.50it/s]
Wrote index to data/knn_index_clean/ : embeddings (10838, 1024), 10838 pairs

---
## Step 2 — the sparse channel

In [10]:
!python3 manage.py sparse_select --config configs/sparse_retrieval.yaml \
    --split val --index_dir data/knn_index_clean

Selecting k=8 (m=4 sparse) for 1323 val sources ...
Loading intfloat/multilingual-e5-large-instruct on device: cuda
Loading weights: 100%|█████████████████████| 391/391 [00:00<00:00, 2549.05it/s]
Dense-only baseline for the redundancy comparison ...
  routes: {'full': 0.0, 'partial': 0.0642, 'dense': 0.9358}
  rarity slots filled: mean 0.072, {'0': 1238, '1': 76, '2': 8, '3': 1, '4': 0}
  queries with >= n irregular terms: {'1': 0.0642, '2': 0.0068, '3': 0.0008, '4': 0.0, '5': 0.0, '6': 0.0}
  mean coverage (routed): 1.0
  intra-set cosine: {'sparse': 0.8995, 'dense_baseline': 0.9002}
Wrote results/sparse_selection_val.json

In [11]:
sel = json.load(open('results/sparse_selection_val.json'))
print('routes            :', sel['route_fractions'])
print('irregular terms/query — mean', sel['query_terms']['mean'],
      'deciles', sel['query_terms']['deciles'])
print('share at or above :', sel['query_terms']['share_at_or_above'])
print('coverage (routed) :', sel['coverage']['mean'])
print('intra-set cosine  :', sel['intra_set_similarity'])

routes            : {'full': 0.0, 'partial': 0.0642, 'dense': 0.9358}
irregular terms/query — mean 0.072 deciles [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3]
share at or above : {'1': 0.0642, '2': 0.0068, '3': 0.0008, '4': 0.0, '5': 0.0, '6': 0.0}
coverage (routed) : 1.0
intra-set cosine  : {'sparse': 0.8995, 'dense_baseline': 0.9002}

### Threshold sweep

`min_query_terms` is the one knob that decides whether the channel exists at all. Selection
is cheap once the index is loaded, so sweep it rather than arguing about it. Each run
writes its own report, leaving the configured run's above intact.

In [12]:
for thr in (1, 2, 3, 4):
    print(f'--- min_query_terms={thr}')
    !python3 manage.py sparse_select --config configs/sparse_retrieval.yaml --split val --index_dir data/knn_index_clean --min_query_terms {thr} --out results/sparse_sweep_val_t{thr}.json 2>&1 | grep -E 'routes|intra-set'

--- min_query_terms=1
  routes: {'full': 0.0, 'partial': 0.0642, 'dense': 0.9358}
  intra-set cosine: {'sparse': 0.8995, 'dense_baseline': 0.9002}
--- min_query_terms=2
  routes: {'full': 0.0, 'partial': 0.0068, 'dense': 0.9932}
  intra-set cosine: {'sparse': 0.9, 'dense_baseline': 0.9002}
--- min_query_terms=3
  routes: {'full': 0.0, 'partial': 0.0008, 'dense': 0.9992}
  intra-set cosine: {'sparse': 0.9002, 'dense_baseline': 0.9002}
--- min_query_terms=4
  routes: {'full': 0.0, 'partial': 0.0, 'dense': 1.0}
  intra-set cosine: {'sparse': 0.9002, 'dense_baseline': 0.9002}

### The min_df floor

In [13]:
for min_df in (2, 10, 20):
    lst = f'results/rarity_train_mindf{min_df}.json'
    print(f'--- min_df={min_df}')
    !python3 manage.py rarity --config configs/sparse_retrieval.yaml --min_df {min_df} --out {lst} 2>&1 | grep -E 'frozen|realized'
    !python3 manage.py sparse_select --config configs/sparse_retrieval.yaml --split val --index_dir data/knn_index_clean --rarity {lst} --out results/sparse_sweep_val_mindf{min_df}.json 2>&1 | grep -E 'routes|rarity slots'

--- min_df=2
  22789 pool terms, 11121 at df >= 2 -> 500 frozen (requested 500)
  2.2% of the vocabulary, realized df [2, 2]
  df histogram (frozen): {'1': 0, '2': 500, '3': 0, '4-9': 0, '10-99': 0, '100+': 0}
  routes: {'full': 0.0, 'partial': 0.0642, 'dense': 0.9358}
  rarity slots filled: mean 0.072, {'0': 1238, '1': 76, '2': 8, '3': 1, '4': 0}
--- min_df=10
  22789 pool terms, 2286 at df >= 10 -> 500 frozen (requested 500)
  2.2% of the vocabulary, realized df [10, 12]
  df histogram (frozen): {'1': 0, '2': 0, '3': 0, '4-9': 0, '10-99': 500, '100+': 0}
  routes: {'full': 0.0008, 'partial': 0.3023, 'dense': 0.6969}
  rarity slots filled: mean 0.386, {'0': 922, '1': 304, '2': 85, '3': 11, '4': 1}
--- min_df=20
  22789 pool terms, 1127 at df >= 20 -> 500 frozen (requested 500)
  2.2% of the vocabulary, realized df [20, 34]
  df histogram (frozen): {'1': 0, '2': 0, '3': 0, '4-9': 0, '10-99': 500, '100+': 0}
  routes: {'full': 0.0113, 'partial': 0.5019, 'dense': 0.4868}
  rarity slots filled: mean 0.775, {'0': 644, '1': 420, '2': 187, '3': 57, '4': 15}

### Worked examples

In [14]:
for ex in sel['examples']:
    print('QUERY :', ex['source'][:90])
    print('  route', ex['trace']['route'], '| terms', ex['trace']['query_terms'],
          '| coverage', ex['trace']['coverage'])
    for e in ex['exemplars']:
        print('   -', e[:90])
    print()

QUERY : جواهر الأسرار فی معارج الأسفار لمن اراد ان یتقرّب بالله المقتدر الغفّار فهنیاً للأبرار الّ
  route partial | terms ['الأسفار', 'الأنهار'] | coverage 1.0
   - و بهدایت کبری و ربوبیّت عظمی مبعوث شوند که تا قلوب مشتاقین و حقایق صافین را بالهامات غیبیّ
   - فأمطر من سحاب فیض فضلک ما تطهّر به افئدة عبادک عمّا یحجبهم عن النّظر الی وجهک و یمنعهم عن
   - اللّهمّ انّی اسألک بالحرف الّتی اذا خرجت من فم مشیّتک ماجت البحار و هاجت الأریاح و ظهرت ال
   - من شرب من الکأس الّتی تدور بها ید رحمتک ینقطع عن دونک و ینجذب بکلمة منه عبادک الّذین رقدوا
   - لو تعرف ما نزّل من قلمی و تطّلع علی خزائن امری و لآلئ اسراری فی بحور اسمائی و اواعی کلماتی
   - طوبی لک بما کنت سائراً فی بلاد الله و کنت آیة الفرح و الاطمینان لأهل البهآء الّذین انقطعوا
   - و اسألک یا الهی باسمک الّذی به امطرت السّحاب و جرت الأنهار و اشتعلت نار الحبّ فی الأشطار ب
   - بشأن الآیة المبارکة فی الأسفار إذا نزلتم واسترحتم المقام الآمن مکان کلّ صلوة سجدة واحدة.

QUERY : و اسأل الله بأن یؤیّدنی بذلک اذ هو ارحم الرّاحمین و معطی السّائلین.
  route partial | terms ['اسأل'] | coverage 1.0
   - اذاً اسئلک یا الهی باسمک الّذی به طیّرت العاشقین فی هوآء ارادتک و اهتدیت به المشتاقین الی
   - اسألک بمظلومیّة نفسک و بابتلائها بین جنود الظّالمین بأن تنزل علیّ من سحاب رحمتک ما یجعلنی
   - ولکن یا مربّی العالم و مالک الامم اسئلک فی هذا الحین الّذی اکون آخذاً بید الرّجآء اذیال رد
   - اسألک بأمطار رحمتک الّتی بها انبتت فی قلوب الموحّدین اوراد الذّکر و البیان و ازهار الحکمة
   - ای رحیمی که ساذج رحمت بابت را ساجد و جوهر عنایت کعبهٴ امرت را طائف از تو سؤال مینمائیم فضل
   - اسألک باسمک الّذی به ارفعت اعلام هدایتک و اشرقت انوار عنایتک و اظهرت سلطان ربوبیّتک و به ظ
   - ایربّ انا الفقیر و انت الغنیّ المتعال فارحمنی ببدایع رحمتک ثمّ ارسل علیّ فی کلّ آن ما احیی
   - اسأل اللّه بک و بالّذین استضآءت وجوههم من انوار وجهک و اتّبعوا ما امروا به حبّاً لنفسک ان

QUERY : و اذا رأیتم هذا کلّه کائناً اعلموا انّ ملکوت الله قد اقتربت.
  route partial | terms ['اعلموا'] | coverage 1.0
   - لو یسمعها احد ما قدّرته فیها حقّ الاصغآء لیطیر الی ملکوت امرک الّذی ینطق فیه کلّ ما خلق فی
   - حضرت یحیی بن زکریّا فرموده آنچه را که مبشّر فرموده قائلاً توبوا لأنّه قد اقترب ملکوت السّم
   - لو تسمع صریر القلم الأعلی و هدیر ورقآء البقآء علی افنان سدرة المنتهی فی ذکر الله موجد الأس
   - ولکن انت برحمتک الّتی سبقت ملکوت ملک السّموات و الأرض قبلت من عبادک ذکرهم و ثنائهم نفسک ال
   - و از این کلمات و اشارات معلوم و ثابت شد که لابدّ در عالم ملک و ملکوت باید کینونت و حقیقتی
   - اشهد بما شهدت الأشیآء و الملأ الأعلی و الجنّة العلیا و عن ورائها لسان العظمة من الأفق الأب
   - لو یطّلع احد علی ما قدّر له فی عوالم الله ربّ العرش و الثّری لیشتعل فی الحین شوقاً لذاک ال
   - ثمّ اعلموا بأنّا ما نخاف من احد الّا الله.